/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        Final.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Judul = new javax.swing.JLabel();
        Bilangan1 = new javax.swing.JLabel();
        Bilangan2 = new javax.swing.JLabel();
        Hasil = new javax.swing.JLabel();
        Angka1 = new javax.swing.JTextField();
        Angka2 = new javax.swing.JTextField();
        Final = new javax.swing.JTextField();
        Penjumlahan = new javax.swing.JButton();
        Pengurangan = new javax.swing.JButton();
        Pembagian = new javax.swing.JButton();
        Perkalian = new javax.swing.JButton();
        Modulo = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Judul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Judul.setText("Kalkulator");

        Bilangan1.setText("Masukkan angka 1");

        Bilangan2.setText("Masukkan angka 2");

        Hasil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Hasil.setText("Hasil");

        Angka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka2ActionPerformed(evt);
            }
        });

        Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalActionPerformed(evt);
            }
        });

        Penjumlahan.setText("+");
        Penjumlahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjumlahanActionPerformed(evt);
            }
        });

        Pengurangan.setText("-");
        Pengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenguranganActionPerformed(evt);
            }
        });

        Pembagian.setText("/");
        Pembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembagianActionPerformed(evt);
            }
        });

        Perkalian.setText("*");
        Perkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerkalianActionPerformed(evt);
            }
        });

        Modulo.setText("mod");
        Modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuloActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Angka1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Angka2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Bilangan2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bilangan1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Penjumlahan)
                                .addGap(18, 18, 18)
                                .addComponent(Pengurangan)
                                .addGap(18, 18, 18)
                                .addComponent(Pembagian)))
                        .addContainerGap(166, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Perkalian)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Modulo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Final, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Hapus)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Judul)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bilangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Angka1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bilangan2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Angka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Penjumlahan)
                    .addComponent(Pengurangan)
                    .addComponent(Pembagian))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modulo)
                    .addComponent(Perkalian))
                .addGap(46, 46, 46)
                .addComponent(Hasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hapus))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void Angka2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void FinalActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void PenguranganActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if (validateInput()) {
            double a1 = Double.parseDouble(Angka1.getText());
            double a2 = Double.parseDouble(Angka2.getText());
            double hasil = a1 - a2;
            Final.setText(Double.toString(hasil));
        }
    }                                           

    private void PenjumlahanActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if (validateInput()) {
            double a1 = Double.parseDouble(Angka1.getText());
            double a2 = Double.parseDouble(Angka2.getText());
            double hasil = a1 + a2;
            Final.setText(Double.toString(hasil));
        }
    }                                           

    private void PembagianActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if (validateInput()) {
            double a1 = Double.parseDouble(Angka1.getText());
            double a2 = Double.parseDouble(Angka2.getText());
            if (a2 != 0) {
                double result = a1 / a2;
                Final.setText(String.valueOf((int)result));
            } else {
                Final.setText("Error");
            }
        }
    }                                         

    private void PerkalianActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if (validateInput()) {
            double a1 = Double.parseDouble(Angka1.getText());
            double a2 = Double.parseDouble(Angka2.getText());
            double hasil = a1 * a2;
            Final.setText(Double.toString(hasil));
        }
    }                                         

    private void ModuloActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if (validateInput()) {
            double a1 = Double.parseDouble(Angka1.getText());
            double a2 = Double.parseDouble(Angka2.getText());
            if (a2 != 0) {
                double result = a1 % a2;
                Final.setText(String.valueOf((int)result));
            } else {
                Final.setText("Error");
            }
        }
    }                                      

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    Angka1.setText("");
    Angka2.setText("");
    Final.setText("");
    }                                     

    private boolean validateInput() {
        String input1 = Angka1.getText();
        String input2 = Angka2.getText();
        
        if (input1.isEmpty() || input2.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tabel tidak boleh ada yang kosong", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try {
            Double.parseDouble(input1);
            Double.parseDouble(input2);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Input salah.(Harus angka)", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Angka1;
    private javax.swing.JTextField Angka2;
    private javax.swing.JLabel Bilangan1;
    private javax.swing.JLabel Bilangan2;
    private javax.swing.JTextField Final;
    private javax.swing.JButton Hapus;
    private javax.swing.JLabel Hasil;
    private javax.swing.JLabel Judul;
    private javax.swing.JButton Modulo;
    private javax.swing.JButton Pembagian;
    private javax.swing.JButton Pengurangan;
    private javax.swing.JButton Penjumlahan;
    private javax.swing.JButton Perkalian;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
